# Generated by Django 3.0.3 on 2020-03-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('coin', models.IntegerField()),
                ('food', models.IntegerField()),
                ('water', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('game_class', models.TextField()),
                ('talents', models.TextField()),
                ('specials', models.TextField()),
                ('armors', models.TextField()),
                ('weapons', models.TextField()),
                ('items', models.TextField()),
            ],
        ),
    ]
