# Generated by Django 3.0.3 on 2020-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='armors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='coin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='items',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='water',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.TextField(null=True),
        ),
    ]
