# Generated by Django 3.0.3 on 2020-03-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20200314_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='talents',
            new_name='abilities',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='dexterity',
            new_name='agility',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='coin',
            new_name='peng',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='game_class',
            new_name='profession',
        ),
    ]
